project:
  type: book

book:
  title: "UCSD Gaps"
  author: "Sarah Nolan"
  date: "01/03/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - C1_Affordable_Learning.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

