---
title: "Academic Outcomes"
editor: visual
---
This is a chapter about academic outcomes at UCSD

```{r}
#| label: run_scripts
#| include: FALSE

source("rscripts/load_packages.R", local = knitr::knit_global())

source("rscripts/functions_clean_data.R" ,local = knitr::knit_global())

source("rscripts/functions_visualize.R" ,local = knitr::knit_global())

```


```{r}
#data is from the UCSD IR -datatable with https://tableau.ucsd.edu/#/views/UGGraduationandRetentionRates2022/TransferGraduationRates?:iid=1

cumu_ftfy<-read_excel("data/cumu_grad_rates.xlsx", sheet="FTFY", na=c("0.000",""))%>%
  label_groups(.)%>%
  mutate(across(perc_6:perc_8, ~na_if(.x,0)))


cumu_t<-read_excel("data/cumu_grad_rates.xlsx", sheet="Transfer",na=c("0.000",""))%>%
  label_groups(.)%>%
mutate(across(perc_2:perc_5, ~na_if(.x,0)))
    
```

Cumulative Graduation Rates

## Undergraduate Overall Graduation Rates

Defined as six years or less for FTFY, defined or four years or less for transfer students. 

```{r}

ftfy_six_2016<-cumu_ftfy%>%
filter(entrycohort=="2016")%>%
  #select the graduate period of interest and make it match the formula's generic column name  - value 
  mutate(value=perc_6)%>%
  select(comp, group, group_label, value)%>%
  mutate(all=filter(., comp=="All")%$% value)%>%
  order_comp_group_all(.)%>%
  create_diff_cols(.)%>%
  #flip factor levels to make a better visual - graduate rates are positive
  mutate(avg_above=fct_rev(avg_above))

plot_text_div(ftfy_six_2016)+
   scale_x_continuous(expand=c(.02,.02), limits=c(.72, .96), breaks=c(.875,.95), labels=c("Student Average",  "Difference from \nAverage"), position="top")+
    scale_y_discrete(expand=c(0,1.2))+
    #build diff box
    #spacing of diff bar is determined on y axis
    geom_rect(data=ftfy_six_2016, aes(xmin=.94, xmax=.96, ymin=-Inf, ymax=Inf), fill="grey") +
    geom_text(data=ftfy_six_2016, aes(label=paste0(round(diff*100,0), "%"), x=.95, y=group_label, color=avg_above), fontface="bold", size=3)+
  labs(title="FTFY Six Years or Less Graduation Rate",
       subtitle ="UCSD FTFY 2016 Entry Cohort",
       caption="Data Source: UCSD IR")
 
 ggsave("viz/academic/ftfy_six_2016.png", width=9, height=5, units="in", dpi=300)
      
```

```{r}
t_four_2018<-cumu_t%>%
filter(entrycohort=="2018")%>%
  #select the graduate period of interest and make it match the formula's generic column name  - value 
  mutate(value=perc_4)%>%
  select(comp, group, group_label, value)%>%
  mutate(all=filter(., comp=="All")%$% value)%>%
  order_comp_group_all(.)%>%
  create_diff_cols(.)



plot_text_div(t_four_2018)+
   scale_x_continuous(expand=c(.02,.02), limits=c(.80, .97), breaks=c(.877,.96), labels=c("Student Average",  "Difference from \nAverage"), position="top")+
    scale_y_discrete(expand=c(0,1.2))+
    #build diff box
    #spacing of diff bar is determined on y axis
    geom_rect(data=t_four_2018, aes(xmin=.95, xmax=.97, ymin=-Inf, ymax=Inf), fill="grey") +
    geom_text(data=t_four_2018, aes(label=paste0(round(diff*100,0), "%"), x=.96, y=group_label, color=avg_above), fontface="bold", size=3)+
  labs(title="Transfer Students Four Years or Less Graduation Rate",
       subtitle ="UCSD Transfer 2018 Entry Cohort",
       caption="Data Source: UCSD IR")
 

```


```{r}
ftfy_four_2018<-cumu_ftfy%>%
filter(entrycohort=="2018")%>%
  #select the graduate period of interest and make it match the formula's generic column name  - value 
  mutate(value=perc_4)%>%
  select(comp, group, group_label, value)%>%
  mutate(all=filter(., comp=="All")%$% value)%>%
  order_comp_group_all(.)%>%
  create_diff_cols(.)%>%
  #flip factor levels to make a better visual - graduate rates are positive
  mutate(avg_above=fct_rev(avg_above))

plot_text_div(ftfy_four_2018)+
   scale_x_continuous(expand=c(.02,.02), limits=c(.53, .84), breaks=c(.736,.83), labels=c("Student Average",  "Difference from \nAverage"), position="top")+
    scale_y_discrete(expand=c(0,1.2))+
    #build diff box
    #spacing of diff bar is determined on y axis
    geom_rect(data=ftfy_four_2018, aes(xmin=.82, xmax=.84, ymin=-Inf, ymax=Inf), fill="grey") +
    geom_text(data=ftfy_four_2018, aes(label=paste0(round(diff*100,0), "%"), x=.83, y=group_label, color=avg_above), fontface="bold", size=3)+
  labs(title="FTFY Four Years or Less Graduation Rate",
       subtitle ="UCSD FTFY 2018 Entry Cohort",
       caption="Data Source: UCSD IR")
 
```
```{r}

t_two_2020<-cumu_t%>%
filter(entrycohort=="2020")%>%
  #select the graduate period of interest and make it match the formula's generic column name  - value 
  mutate(value=perc_2)%>%
  select(comp, group, group_label, value)%>%
  mutate(all=filter(., comp=="All")%$% value)%>%
  order_comp_group_all(.)%>%
  create_diff_cols(.)%>%
  filter(group!="American Indian")



plot_text_div(t_two_2020)+
   scale_x_continuous(expand=c(.02,.02), limits=c(.43, .68), breaks=c(.566,.67), labels=c("Student Average",  "Difference from \nAverage"), position="top")+
    scale_y_discrete(expand=c(0,1.2))+
    #build diff box
    #spacing of diff bar is determined on y axis
    geom_rect(data=t_two_2020, aes(xmin=.66, xmax=.68, ymin=-Inf, ymax=Inf), fill="grey") +
    geom_text(data=t_two_2020, aes(label=paste0(round(diff*100,0), "%"), x=.67, y=group_label, color=avg_above), fontface="bold", size=3)+
  labs(title="Transfer Students Two Years or Less Graduation Rate",
       subtitle ="UCSD Transfer 2020 Entry Cohort",
       caption="Data Source: UCSD IR")
 
```

